version: 1
disable_existing_loggers: False

formatters:
  simple_formatter:
    format: "[%(asctime)s] [%(levelname)s] %(name)s: %(message)s "

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple_formatter

loggers:
  main:
    handlers: [console]
    level: INFO
    propagate: False

root:
  handlers: [console]
  level: WARNING